site_name: QuakeFlow
site_description: 'QuakeFlow: a Scalable Deep-learning-based Earthquake Monitoring Workflow with Cloud Computing'
site_author: 'Weiqiang Zhu'
docs_dir: docs/
repo_name: 'wayneweiqiang/QuakeFlow'
repo_url: 'https://github.com/wayneweiqiang/QuakeFlow'
nav:
    - Home: index.md
theme:
  name: 'material'
plugins:
  - mkdocs-jupyter