site_name: "QuakeFlow"
site_description: 'QuakeFlow: a Scalable Deep-learning-based Earthquake Monitoring Workflow with Cloud Computing'
site_author: 'Weiqiang Zhu'
docs_dir: docs/
repo_name: 'wayneweiqiang/QuakeFlow'
repo_url: 'https://github.com/wayneweiqiang/QuakeFlow'
nav:
    - Pipeline Overview: README.md
    - Data Downloading: data.md
    - Denoising: deepdenoiser.md
    - Phase Picking: phasenet.md
    - Phase Association: gamma.md
    - Earthquake Location: location.md
theme:
  name: 'material'
plugins:
  - mkdocs-jupyter